#page title
page_title: Gemairo - Stats voor Magister # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1529746917 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: https://apps.apple.com/nl/app/magiscore-magister-stats/id1529746917?l=en # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://play.google.com/store/apps/details?id=app.netlob.magiscore # Enter Google Play Store URL.
presskit_download_link:
  https://github.com/netlob/magiscore # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: https://cdn.discordapp.com/attachments/830562126560231464/959193878391578635/gemairo_logo_new_copy.webp # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Gemairo # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Gratis # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Check allemaal coole dingen over je cijfers enzo

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Sjoerd Bolten (h.o.d.n Gemairo Group B.V.)
your_link: https://sjoerd.dev
your_city: The Netherlands
email_address: info@magiscore.nl
facebook_username:
instagram_username: sjoerdbolten
twitter_username: netlob
github_username: netlob
youtube_username: netlob

# Feature List                            Edit, add or remove features to be presented.
features:
  # - title                                 : GitHub Pages Jekyll Theme
  #   description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
  #   fontawesome_icon_name                 : magic

  # - title                                 : iPhone Device Preview
  #   description                           : Preview your app in the context of an iPhone device. Five different device colors included.
  #   fontawesome_icon_name                 : mobile

  # - title                                 : Video Support
  #   description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
  #   fontawesome_icon_name                 : play-circle

  - title: Synchroniseer
    description: In minder dan een seconde kun je checken of je nieuwe cijfers hebt, en heb je deze, dan zullen ze direct worden toegevoegd aan de statistieken en berekeningen
    fontawesome_icon_name: sync

  - title: Thema's
    description: Standaard is Magiscore in lichte modus. Wil je donkere modus? Dat kan je aanzetten in de instellingen.
    fontawesome_icon_name: adjust

  - title: Gratis
    description: Magiscore is gratis en voor iedereen te downloaden via de App Store én Play Store
    fontawesome_icon_name: euro-sign

  # - title                                 : Smart App Banner
  #   description                           : Display a smart app banner on iOS devices.
  #   fontawesome_icon_name                 : arrow-alt-circle-down

  # - title                                 : Social Links
  #   description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : link

  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle

  # - title                                 : # New Feature Title
  #   description                           : # New Feature Description
  #   fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: blue # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
